### ISSUE TITLE
issues testing from octave

### ISSUE THREAD

**Issue by fabianp** [ayrna/orca#48] opened 2018-09-16 18:17 UTC
Hi,

I'm running orca from Octave installed from ubuntu 18.10.

Installation goes fine but when I try to run the tests (from Octave shell) I get the following errors. 

```
warning: struct: converting a classdef object into a struct overrides the access restrictions defined for properties. All properties are returned, including private and protected ones.
warning: called from
    fieldnames at line 47 column 11
    parseArgs at line 114 column 29
    POM at line 56 column 13
    pomTest at line 7 column 14
    runtestssingle at line 35 column 5
panic: Segmentation fault -- stopping myself...
.........................
Performing test for POM
Accuracy Train 0.408889, Accuracy Test 0.333333
Test accuracy matchs reference accuracy
Processing redsvmTest.m...
attempting to save variables to 'octave-workspace'...
error: octave_base_value::save_binary(): wrong type argument 'object'
```

any clue on what is causing the error?

**Comment by pagutierrez** [comment] 2018-09-18 09:05
Hi Fabian,

Thanks for your comment. Could you please specificy what version of Octave are you using? We have some issues with recent versions...

Best regards,

Pedro

**Comment by fabianp** [comment] 2018-09-18 14:51
Hi Pedro,

I'm using version 4.2.2, which is the one that comes bundled with Ubuntu 
18.10 LTS

**Comment by javism** [comment] 2018-09-19 16:55
Thanks. I've reproduced the errors in a clean installation of Ubuntu (we used Linux Mint 18.3 previously so we didn't got the error). 

I have fixed some issues regarding compilation with newer versions. I suspect that there is some problem with some shared env variables since the tests are ok when run individually. I'll work on that during the weekend.

**Comment by fabianp** [comment] 2018-09-20 03:45
thanks!

**Comment by javism** [comment] 2018-09-26 08:54
After examining the issues. The tests (single and cv) works if we do 'clear all' before each test. I've examined path, variables and environment and I can't find the problem in Octave 4.2.2 (it worked previously in 4.2). We are properly cleaning the path after every fit/predict call that needs C code. 

My temporal solution proposal is to rewrite the tests to add a 'clear all' at the very beginning and keep the issue open. This does not sound weird at all in Matlab/Octave since many scripts start with 'clear all'.

**Comment by javism** [comment] 2018-10-01 21:58
Hi @fabianp, 

This issues should be now fixed in Octave +4.2.2 in Ubuntu. Also, I test the changes in Matlab 2017b (Windows and Linux). Please, let us now if this works for you. I'll merge to master now.

**Comment by javism** [comment] 2019-04-01 15:59
Master branch passes tests for Octave 4.2 (official PPA) and Octave 4.4 (Ubuntu 18.10). 

Octave 4.2 is in travis CI now, so we should be able of detecting these type of problems in the future. 

Thanks.

**Comment by javism** [comment] 2019-05-03 10:09
Tests are ok in travis https://travis-ci.org/ayrna/orca

**Closed** 2019-05-03 10:08 UTC
